services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest 
    volumes:
      - /root/backrest/data:/data
      - /root/backrest/config:/config
      - /root/backrest/cache:/cache
      - /root/:/userdata # mount your directories to backup somewhere in the filesystem
    environment:
      - BACKREST_PORT=0.0.0.0:9898
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
    restart: unless-stopped
