services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - TZ=America/Los_Angeles
      - CLI_ARGS= #optional
    volumes:
      - /root/duplicati/config:/config
      - /root/duplicati/backups:/backups
      - /root/:/source
    ports:
      - 8200:8200
    restart: unless-stopped
